# Generated by Django 5.1.3 on 2024-11-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('lid', models.CharField(max_length=15, primary_key='lid', serialize=False)),
                ('loantype', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('aadhar', models.IntegerField()),
                ('documents', models.CharField(max_length=15)),
            ],
        ),
    ]
